apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi-deployment
spec:
  selector:
    matchLabels:
      app: customerapi
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: customerapi
        version: v1
    spec:
      containers:
      - name: customerapi-container
        image: acrifsaks.azurecr.io/nla/customerapi:1.1
        ports:
        - containerPort: 80
          protocol: TCP
          name: custapi-port