apiVersion: v1
kind: Service
metadata:
  name: customerapi
  labels:
    app: customer-api
    service: customerapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: customerapi