apiVersion: v1
kind: Service
metadata:
  name: customerapi-service
spec:
  type: NodePort
  selector:
    app: customerapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: custapi-port
      nodePort: 30080