apiVersion: v1
kind: Service
metadata:
  name: customerapi-service
spec:
  type: ClusterIP
  selector:
    app: customerapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: custapi-port